### ISSUE TITLE
When building from dockerfile unable to load web interface

### ISSUE THREAD

**Issue by b34rd-tek** [vulnman/vulnman#145]
### What is the question?

I have built vulnman from the dockerfile but any request to web interface just returns Bad Request 400 errors.

![image](https://user-images.githubusercontent.com/81767471/167032617-06424e8b-f41b-4642-95cf-33f08937a724.png)

Here are my config files:

docker-compose.yml
```
version: '3'

services:
  vulnman-web:
    image: ghcr.io/vulnman/vulnman:latest
    volumes:
      - './local_settings.py:/app/local_settings.py'
      - '/tmp/volumes/vulnman/static:/app/static_files'
    environment:
      DJANGO_SUPERUSER_PASSWORD: dontusethispassword
      DJANGO_SUPERUSER_USERNAME: vulnmanadmin
      DJANGO_SUPERUSER_EMAIL: vulnman@test.com
    depends_on:
      - db
      - celery

  celery:
    image: ghcr.io/vulnman/vulnman:latest
    entrypoint: celery -A vulnman worker -l INFO
    volumes:
      - './local_settings.py:/app/local_settings.py'
      - '/tmp/volumes/vulnman/static:/app/static_files'
    depends_on:
      - redis

  db:
    image: postgres:14.2-alpine
    volumes:
      - '/tmp/volumes/vulnman/db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: dontusethispassword
      POSTGRES_USER: vulnman_db_user
      POSTGRES_DB: vulnman

  redis:
    image: "redis:alpine"

  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - '/tmp/volumes/nginx/config:/config'
      - './docker/nginx.conf:/config/nginx/site-confs/default'
      - '/tmp/volumes/vulnman/static:/config/www/static'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - vulnman-web
```
local_settings.py
```
# This is an example settings file for vulnman


# Enable debug mode. DONT USE IN PRODUCTION ENVIRONMENT!
# DEBUG = True

# Allowed Hosts
# set this to the hostnames of allowed to be used in the Host HTTP header
ALLOWED_HOSTS = ["vulman-web","localhost"]

# Required Setting:
CSRF_TRUSTED_ORIGINS = ['http://localhost','http://127.0.0.1']


# CSS theme
# VULNMAN_CSS_THEME = "flatly"

# #################
# Database Settings
# #################
# uncomment the postgres section, if you are using the docker image
#
# Postgres Example:
#
DATABASES = {
 'default': {
   'ENGINE': 'django.db.backends.postgresql',
   'HOST': 'db',
   'NAME': 'vulnman',
   'USER': 'vulnman_db_user',
   'PASSWORD': 'dontusethispassword',
 }
}


# #########
# Reporting
# #########

# Report Templates
REPORT_TEMPLATES = {
   "default": {
       "CSS": ["report.css", "fontawesome.min.css"]
   }
}


# Add information about your company that is displayed in the report
REPORT_COMPANY_INFORMATION = {
    "name": "Vulnman",
    "street": "No Street 54",
    "zip": "123456 Berlin, Germany",
    "homepage": "https://vulnman.github.io/vulnman",
    "contact": "contact@example.com"
}


# ########
# Security
# For further harding checks see https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# Note: the SECRET_KEY value is uniquely auto generated by default for vulnman installations
# ########

# Set this to True to avoid transmitting the CSRF cookie over HTTP accidentally.
# Default: True
CSRF_COOKIE_SECURE = True

# Set this to True to avoid transmitting the session cookie over HTTP accidentally.
# Default: True
SESSION_COOKIE_SECURE = True


######################
# Celery Worker
######################
# Required for Docker!
CELERY_BROKER_URL = "redis://redis:6379"
```
